// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agthigsdycuzgthahrwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFndGhpZ3NkeWN1emd0aGFocnd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNjAwODEsImV4cCI6MjA2OTkzNjA4MX0.cJRCoKsVduFoigzJuw8DKK-l_D2iFL6amP6cw2yjee8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});