// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pktzilzbdnolzoyzobba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrdHppbHpiZG5vbHpveXpvYmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjMwODgsImV4cCI6MjA3MDU5OTA4OH0.bjLTF2_HTejQ5LjBI5W253AgKBoMwBO7wRgOUNcxKtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});